version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frete_rapido_api
    ports:
      - "8080:8080"
    environment:
      - API_PORT=${API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=${DB_SSL_MODE}
      - FRETE_RAPIDO_API_URL=${FRETE_RAPIDO_API_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - freterapido-net

  db:
    image: postgres:14-alpine
    container_name: frete_rapido_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - freterapido-net

volumes:
  postgres_data:

networks:
  freterapido-net:
    driver: bridge
